[profile.default] # all profiles inherit from this
solc = '0.8.13'
src = 'contracts'
out = '/crates/bindings' # default
test = 'test' # default
libs = ['lib']
cache = false # !important! breaks echidna if cache = true.
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
    'solstat/=lib/solstat/src/',
]