[profile.default] # all profiles inherit from this
src = ''
out = 'out/' # default
test = 'test' # default
libs = ['contracts']
cache = false # !important! breaks echidna if cache = true.
remappings = [
    'forge-std/=contracts/forge-std/src/',
    'solmate/=contracts/solmate/src/',
    'solstat/=contracts/solstat/src/',
]
