[package]
name = "bindings"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = "1.0.0"
serde_json = "1.0.79"