rpc_url = "https://eth-mainnet.g.alchemy.com/v2/I93POQk49QE9O-NuOz7nj7sbiluW76it"

[see]
token0 = "ETH"
token1 = "USDC"
bp = "30"

[sim]
timestep = 0.0027397
timescale = "years"
num_steps = 365
initial_price = 4
drift = 0.1
volatility = 0.7
seed = 887
mean = 1
theta = 0.4
