[package]
name = "bindings_old"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "=1.0.2"
serde_json = "1.0.79"