[package]
name = "docs"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[build-dependencies]
skeptic = "0.13.7"
tokio = "1.36.0"

[dev-dependencies]
skeptic = "0.13.7"
arbiter-core.workspace = true
arbiter-bindings.workspace = true
revm-primitives.workspace = true